# Generated by Django 3.1.3 on 2020-11-11 20:20

from django.db import migrations, models
import django.db.models.deletion
import organisations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField(validators=[organisations.models.validate_is_phonenumber])),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('website', models.CharField(default=None, max_length=255, null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='organisations/')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('0', 'Mandag'), ('1', 'Tirsdag'), ('2', 'Onsdag'), ('3', 'Torsdag'), ('4', 'Fredag'), ('5', 'Lørdag'), ('6', 'Søndag')], default=None, max_length=1)),
                ('time_open', models.TimeField(default=None, validators=[organisations.models.validateTimeFormInput])),
                ('working_time', models.CharField(max_length=255, validators=[organisations.models.validateTimeFormInput])),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
        ),
    ]
